communitiesuk/funding-service-design-application-store

requirements-dev.txt
requirements.in
requirements.txt

Updated reqs so that psycopg2-binary is used instead, fixes deployment bug.

:card_file_box: Changed postgres req

---

.github/workflows/manual-dev-deploy.yaml
Dockerfile
config/envs/dev.py
requirements-dev.in
requirements-dev.txt
requirements.in
requirements.txt

Psycopg2 is now included differently for dev or non-dev requirements:
- `requirements-dev` uses `psycopg2` as we need the source for running docker locally
- `requirements` uses `psycopg2-binary` as it includes everything needed to run on paas.
Also:
- Fixed manual deploy dev workflow
- updated the postgres url in dev config

BAU - Fixing psycopg2 dependency

---

manifest.yml

Reverts communitiesuk/funding-service-design-application-store#31
We need to revert this as it won't log currently unless we're using Gunicorn to run the app with our logging templates.

Revert "BAU : Added logit to manifest"

---

manifest.yml

Implements utils feature to pass through the `GITHUB_SHA` for Sentry release

FS-1677: Pass through GITHUB_SHA to app

---

db/models/aggregate_functions.py

We were getting an exception `'NoneType' object has no attribute 'group'`  as we were attempting to get a regex match group on a None value when postcode was not populated. Couple of fixes to address this: 
* Only attempt regex match if field is not None
* Use regex to match form builder

FS-1896: fix postcode lookup in report

---

db/models/aggregate_functions.py
db/models/applications.py

Previously we made a separate call for forms for each applications, this uses the foreign key to establish a one-to-many relationship so the forms are returned as part of the application model.

FS-1928: get forms using foreign key instead of separate lookup

---

db/models/applications.py

Previously we were making an unsafe lookup on the language enum, so existing applications without a language set were throwing an exception:
```
AttributeError
'NoneType' object has no attribute 'name'
```
this fixes it to the intended behaviour of falling back to `en` if not set.
Note: we probably should test this but the existing test setup makes this difficult so would rather get this hot-fix out as-is.

BAU: safe lookup on language

---

db/models/aggregate_functions.py

Spotted in the course of another story:
Previously this was unintentionally always evaluating to True as `"gwybodaeth-am-y-prosiect"` was always truthy due to missing brackets.

BAU: fix boolean logic

---

external_services/models/fund.py

On PaaS we were getting the exception: 
```
ImportError: cannot import name 'Self' from 'typing' (/usr/local/lib/python3.10/typing.py)
``` 
because we were trying to use a Python 3.11 feature on Python 3.10

FS-2022: remove python 3.11 feature

---

Dockerfile

Since `psycopg2-binary` was bumped in https://github.com/communitiesuk/funding-service-design-application-store/pull/97 the app was failing to start up within docker compose with the following error:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SCRAM authentication requires libpq version 10 or above
```
Add a workaround to fix this, see https://stackoverflow.com/a/73566004 for context
To test this locally you can run from the docker-runner
```
docker compose build application-store --no-cache && docker compose up application-store
```
and the app should start successfully

BAU: add workaround to fix dockerfile

---

db/schemas/application.py

We were erroneously defaulting this value in the model when the frontend can handle a `None` value.

BAU: Don't default project title as frontend can handle None value

---

db/schemas/application.py
tests/test_routes.py

https://digital.dclg.gov.uk/jira/browse/FS-2047
500 on tasklist for certain applications (now known to be those with no language set in db - older ones) when on UAT

patch language default on request

---

external_services/models/notification.py

With the nested log message in content we got an exception in the logging library:
```
2022-12-09T16:52:26.28+0000 [APP/TASK/reminder_email/0] ERR log_record["message"] = log_record["message"].format(
2022-12-09T16:52:26.28+0000 [APP/TASK/reminder_email/0] ERR ValueError: Max string recursion exceeded
2022-12-09T16:52:26.28+0000 [APP/TASK/reminder_email/0] ERR Call stack:
2022-12-09T16:52:26.28+0000 [APP/TASK/reminder_email/0] ERR File "/home/vcap/app/./scripts/send_application_reminder.py", line 98, in <module>
```
Fix by no longer logging the full application contents.

FS-1674: remove content logging 

---

.github/workflows/manual-dev-deploy.yaml

Added environment var for the Assessment url, so that the assessment e2e test doesn't fail to run in the pipeline.
N/A
N/A

BAU - Add env var for Assessment e2e test

---

.github/workflows/manual-dev-deploy.yaml

Disabling e2e tests on Dev as it's giving false positives on some test runs. This is mainly due to the environment being constantly deployed per commit which disrupts the e2e test run.
Evidence that e2e application and assessment passes when running against Test env with the e2e tests not running against Dev:
https://github.com/communitiesuk/funding-service-design-frontend/actions/runs/4222595381
N/A
N/A

BAU - Disable e2e tests running against Dev env

---

.github/workflows/tag-to-release.yaml

Since moving to an Enterprise org it appears GITHUB_TOKEN has defaulted to restricted permissions as described in https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token so we need to specify the correct permissions for our workflows.
- [ - ] Unit tests and other appropriate tests added or updated
- [ - ] README and other documentation has been updated / added (if needed)
- [ - ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

tagging action permissions

---

requirements-dev.txt
requirements.in
requirements.txt

This reverts commit 2bb0c4f7b00ddea1680ccf76a535548697032c4f.
The version bump of flask-sqlalchemy from 2.5.1 to 3.x.x causes the unit tests to fail, this need investigating and fixing.
https://digital.dclg.gov.uk/jira/browse/FS-2382

Revert "Bump flask-sqlalchemy from 2.5.1 to 3.0.3 (#134)"

---

requirements-dev.txt
requirements.in
requirements.txt
tests/conftest.py

Fixing app crashes on test because the new utils package was requiring pytest at runtime. This PR brings in a new version of utils that fixes that, and updates the package name accordingly.
- [ n/a] Unit tests and other appropriate tests added or updated
- [ n/a] README and other documentation has been updated / added (if needed)
1. Install dependenices
2. Remove pytest using `pip uninstall pytest`
3. Run app using `flask run`, app should start without import errors
n/a

utils bump to fix imports

---

README.md

Added documentation for readme around running the `send_application_on_closure` script to send unsubmitted applications out once the deadline has passed. No code changes.
N/A

FS-2565 added script docs to readme

---

.gitignore
.vscode/launch.json
.vscode/settings.json

Added workspace settings and launch configurations for vs code to make debugging easier and standardise linting
- Use VS Code
- Clone this branch
- Checkout the branch https://github.com/communitiesuk/funding-service-design-docker-runner/tree/bau-debug-containers of the docker runner
- Run `docker compose build fund-store` to rebuild this app
- Run `docker compose up fund-store` and run the debug config `Docker-Runner fund-store`. Set a breakpoint in the fund-store and the debugger will allow you to step through.

bau adding vs code launch configs

---

db/queries/application/queries.py

This ticket includes the fix for cof r3w1 where project name was not displayed in the dashboard. This problem was cause due to differently named forms and fields. We have now updated the checks in the update_project_name() function to be more general when looking for an updated project name.

fs-2740-project-name

---

config/envs/default.py
config/envs/unit_testing.py
db/queries/application/queries.py
external_services/aws.py
tests/test_aws.py
tests/test_queries.py
tests/test_routes.py

- Add skipped test for TDD
- Add aws file for getting file metadata
- When submitting application, grab the & commit
---
Fill out and submit an application! 
Download the text file emailed to you, and the filename(s) should now be visible!

FS-2842: Get filenames during submission

---

db/queries/application/queries.py
external_services/models/fund.py
tests/conftest.py
tests/test_routes.py

As not all funds support welsh, we need to ensure that even if a user has welsh selected as their frontend language (eg. from the all funds dashboard) they cannot start an application in welsh if the fund does not support it.
1. Pull this branch, plus the below branches of other repos and run in docker-runner. 
2. Make sure COF and NS data are in the DB. 
3. Login to the service and go to the 'View all applications' link at the top. 
4. Switch to Welsh
5. Scroll down to Night Shelter and click 'view applications from all rounds/windows'
6. The page should display in Welsh. Start a new applicaiton.
7. The application should be started in English.
Linked branches:
- …

FS-2826 prevent welsh application if fund is english only

---

db/queries/reporting/queries.py
tests/test_reports.py

https://digital.dclg.gov.uk/jira/browse/FS-2981
Patch to allow the retirval of nstf organisation name when running the reports
pytest

Patch: add nstf org-name field to report mapping

---

api/routes/application/routes.py
openapi/api.yml

- Add option `dont_send_email` to the `submit` application endpoint
- By default is `True` as we should be sending emails
- However, if we force submit, sometimes we may not want to send the email, so good to have the option
---

BAU: Add option to not send notification when submitting

---

.pre-commit-config.yaml
api/routes/application/routes.py
db/migrations/env.py
db/queries/application/queries.py
db/queries/reporting/queries.py
external_services/aws.py
external_services/data.py
external_services/http_methods.py
external_services/models/fund.py
external_services/models/notification.py
openapi/api.yml
openapi/components.yml
openapi/utils.py
tests/helpers.py
tests/seed_data/seed_db.py
tests/test_queries.py
tests/test_reports.py

Updated existing `get_applications_statuses_report` function to accept an optional `format` param to allow returning the data in json so we can consume it from assessment (defaults to csv).
Updated the format to breakdown numbers by fund and round so we can populate the assessment dashboard with just one call to application store (rather than one per round).
Pull this branch and run locally. Then visit the following URLs:
- http://localhost:3002/applications/reporting/applications_statuses_data?format=json Should give you JSON data in the response
- http://localhost:3002/applications/reporting/applications_statuses_data should respond with a csv file as an attachment, as now.
The data in both responses should be the same, just different formats.

FS-3331 adding json format

---

.env.development
.github/workflows/manual-dev-deploy.yaml
.pre-commit-config.yaml
README.md
config/envs/unit_testing.py
copilot/environments/addons/funding-service-magic-links.yml
copilot/fsd-application-store/addons/fsd-application-store-cluster.yml
pytest.ini
tests/README.md

https://dluhcdigital.atlassian.net/browse/FS-3441
- Added pre-commit 'Yelp/detect-secrets' to prevent committing of secrets to code base
- Ignore false positives by marking them with `pragma: allowlist secret`
- disabled the plugin `HexHighEntropyString` which tend to detect lot of false positives
- Add a secret/API key/password to any of the file type
For eg. `API_KEY= "125fdfbdjhbj5989"`
- stage the file & commit it.
- Notice the commit is failed with errors.

FS-3441 added yelp hook for secrets

---

.env.development
.github/workflows/manual-dev-deploy.yaml
.pre-commit-config.yaml
README.md
config/envs/unit_testing.py
copilot/environments/addons/funding-service-magic-links.yml
copilot/fsd-application-store/addons/fsd-application-store-cluster.yml
db/queries/statuses/queries.py
external_services/models/round.py
pytest.ini
tests/README.md
tests/test_application_status.py

Adding support for 'mark this section as complete' at the end of each section.
Updated status calculation to use this field.
Goes with the following PRs:
https://github.com/communitiesuk/digital-form-builder/pull/309
https://github.com/communitiesuk/funding-service-design-frontend/pull/393
https://github.com/communitiesuk/funding-service-design-fund-store/pull/125
_A brief description of the pull request_
Update a round to have `markAsCompleteEnabled=true`
Start an application in that round
Complete a section and you should see the 'mark this section as complete' radio fields on the summary
Select 'No'
Back on the tasklist the section should show as 'In PRogress'
Go through the section again and choose 'yes' on …

Fs 3356 mark as complete

---

copilot/fsd-application-store/addons/fsd-application-store-cluster.yml

https://dluhcdigital.atlassian.net/browse/FS-3457
Change description
Add in Bastion's security group into the fsd-application-store DB's inbound rules.
Tested by using the aws ssm connection through bastion and being able to connect into the postgres DB.
[n/a] Unit tests and other appropriate tests added or updated
[n/a] README and other documentation has been updated / added (if needed)
Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
How to test
If manual testing is needed, give suggested testing steps
Screenshots of UI changes (if applicable)

FS-3457 - Add ingress to DB to allow Bastion connectivity

---

scripts/README.md

Maintaining single source of truth, the script `send_application_on_closure `execution docs are added to the confluence page and README.md directed to confluence page

readme-updated-for-script-send-application-on-closure

---

config/key_report_mappings/cof_r3w2_key_report_mapping.py
config/key_report_mappings/cyp_r1_key_report_mapping.py
config/key_report_mappings/mappings.py
db/queries/feedback/queries.py
tests/test_queries.py

- Added CYP report mapping
- Fixed export application feedback information link for CYP
- Checkout the branch
- Rebuild the container
- Go to swagger & test the API

Added CYP report mappings

---

config/key_report_mappings/dpif_r2_key_report_mapping.py
config/key_report_mappings/mappings.py
db/queries/feedback/queries.py
tests/test_all_feedbacks.py

https://dluhcdigital.atlassian.net/browse/FS-3669
Added DPIF fund report mappings, which is required for extracting applicants email & organisation for export feedback report link on assessment
- Checkout the branch
- Rebuild the container
- Go to swagger & test the API

FS-3669 add report mappings for CYP

---

openapi/components.yml

[Stack Trace](https://funding-service-design-team-dl.sentry.io/share/issue/0fd5ccbb471c46c99f8dd4780686a054/#exception)
```
Newest
NonConformingResponseBody
'2023-12-05T12:17:07.188422' is not a 'date-time'
Failed validating 'format' in schema['properties']['date_submitted']:
{'format': 'date-time', 'type': 'string'}
On instance['date_submitted']:
'2023-12-05T12:17:07.188422'
```
---

FS-3855: Remove date-time from openapi schema

---

openapi/api.yml

The endpoint  GET /applications now accepts array of status_only as well as string

refactor-endpoint/FS-3845-send-application-reminder-script

---

api/routes/application/routes.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-4175
The lead contact name is Capitalised when posting contents to the notification service for COF-EOI  fund round

FS-4175-capitalize-full-name-for-lead-contact-when-sending-invite

---

api/routes/application/routes.py
config/envs/default.py
db/queries/application/queries.py
openapi/api.yml
tests/test_routes.py

FS-4287: adding q and a file creation to application store based on a param and if the param is sent then only file will be send as a base64 encoded.
https://dluhcdigital.atlassian.net/browse/FS-4287 
adding q and a file creation to application store based on a param and if the param is sent then only file will be send as a base64 encoded.
based on the with_questions_file=true query param it will send the file details other wise it will work as is

FS-4287: adding q and a file creation to application store based on a param and if the param is sent then only file will be send as a base64 encoded.

---

tests/seed_data/application_data.py

The old COF support email was using the levellingup domain ( [cof@levellingup.gov.uk](mailto:cof@levellingup.gov.uk) ). This has been updated to the communities domain ( [cof@communities.gov.uk](mailto:cof@communities.gov.uk) )

Update support email to communities from levellingup

---

copilot/fsd-application-store/manifest.yml

This will help us migrate from the "microservice"-y fund-store to a more consolidated pre-award-stores service.
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-108

Read fund-store host from parameter store
