api/namespace/fund/routes.py

FS-716
Remove DELETE endpoint in Application Store

Fs 716 remove delete endpoint

---

config.py
external_services/data.py
tests/api_data/get_endpoint_data.json
tests/helpers.py

- References to deprecated round store api removed
- Fund store endpoints updated to include fund round and rounds endpoints

FS-967 fund api endpoints updated

---

Dockerfile

Add dockerfile to use as part of local development environment

FSD-670: add dockerfile

---

.flaskenv
Dockerfile
manifest.yml

Updated docker file to not use slim-bullseye so that gcc is included and `ruamel-yaml-clib` works.
Also added content to .flaskenv which was empty so it couldn't run locally

Fixed docker file and .flaskenv

---

.github/workflows/tag-to-release.yaml
pytest.ini

- Adds the exciting release workflow...which runs when you tag a commit!
- Also ~~fixes~~ utilises the infamous "no FLASK_ENV" ~~bug~~ feature

bau-tag-to-release

---

api/namespace/applications/helpers/helpers.py
manifest.yml

FUND_STORE_API_HOST not defined in the manifest.yml

Fix fund host ref

---

manifest.yml

We added FLASK_ENVs with corresponding values to the manifest.

added FLASK_ENVs to manifests

---

manifest.yml
scripts/run_migrations_paas.py

bau-Added db migrations scripts

---

manifest.yml

BAU : Added logit to manifest

---

config/envs/production.py

We need this config on all PaaS environments.

FS-987: fix database URL on production

---

api/routes/application/routes.py
config/envs/default.py
config/envs/development.py
config/envs/unit_testing.py
db/models/aggregate_functions.py
db/models/applications.py
external_services/http_methods.py
external_services/models/notification.py
requirements-dev.txt
requirements.txt
tests/conftest.py
tests/test_routes.py

The /submit application route was failing before a notification could be sent due to a datetime parse error when preparing the POST json. This has been corrected and logging added to assist in future debugging.
https://digital.dclg.gov.uk/jira/browse/FS-1397

Fs 1397 fix submit notification

---

db/models/aggregate_functions.py
tests/test_routes.py

Project name field is not grabbing the project name from Project Information after selecting yes

Fs 1508 project name update bug

---

db/models/applications.py
requirements-dev.txt
requirements.txt

As part of reviews with design we needed to update the placeholder text that we use for untitled applications from "Project details not filled in" to "Untitled project"

Fixing untitled project name text

---

requirements-dev.txt
requirements.in
requirements.txt

Changed `fsd_utils` to `1.0.0`, pulled from pypi

fsd-utils version

---

api/routes/application/routes.py
db/models/aggregate_functions.py
tests/test_routes.py

The form marks itself as "Completed" when I don't click the "Save and Continue" button in the "Check your answers" page

FS-1476 Update Form Completed_on Logic

---

config/envs/default.py

spelling correction for form name  inclusiveness-and-integration

form name (inclusiveness-and-integration) spelling correction

---

tests/api_data/get_endpoint_data.json

The only references in this PR to the application list in the account store was within the test data.

FS-1521-remove-app-list-account-store

---

app.py
manifest.yml
requirements-dev.txt
requirements.in
requirements.txt

Adds sentry integration using utils function

FS-1401: add sentry integration

---

api/routes/application/routes.py

Add additional logging to aid debugging this on production

FS-1896: add logging in value error case

---

api/routes/application/routes.py
db/models/aggregate_functions.py
db/models/applications.py
tests/test_reports.py

* Refactors status report to format closer to that currently being supplied to COF
* Optimises query (previously we were getting whole applications and then counting them in memory, now we just count the status field in SQL)

FS-1917: refactor status report

---

db/models/aggregate_functions.py

Previously the query logic was copy-pasted between the single application query and all applications
This combines them into a single function with an optional argument
This makes future refactoring easier as the logic is just in one place.

FS-1928: combine multiple and single query functions

---

api/routes/application/routes.py
db/queries/reporting/queries.py
openapi/api.yml
tests/test_reports.py

In order to meet reporting requirements, adds a `status` query param to allow us to report on applications which are not submitted.

FS-1674: status query param on report

---

.github/workflows/manual-dev-deploy.yaml
config/envs/unit_testing.py
db/models/application/applications.py
external_services/data.py
external_services/http_methods.py
openapi/api.yml
requirements-dev.txt
requirements.txt
scripts/send_application_on_closure.py
tests/helpers.py
tests/test_send_app_on_closure.py

Updates to script to send emails to applicants who have applications that are not submitted. Added error handling and unit tests

Fs 2073 unsubmitted apps

---

openapi/components.yml

Fix to solve application validation failing as forms is returned as an array not an object

fix forms data type to array

---

pytest.ini
requirements-dev.txt
requirements.in
requirements.txt
tests/test_routes.py

Bump utils version to bring in COF_R2W3 data
Also updated tests to work with changes to healthcheck logic in that utils version

Fs 2180 cof r2w3

---

db/queries/statuses/queries.py
tests/test_routes.py

Form should now update to in progress if an optional question on the first page

Fs 1991 optional status update

---

requirements-dev.txt
requirements.in
requirements.txt

Updated utils to latest to pickup changes in how the default_round_id is calculated

bumped utils version

---

.github/workflows/manual-dev-deploy.yaml

https://digital.dclg.gov.uk/jira/browse/FS-1200
Added assessment store url to enable performance tests for Assessment store.
N/A
N/A

FS-1200: Enable performance tests for Assessment store to run in the pipelines

---

.github/workflows/manual-dev-deploy.yaml

Copied concurrency keys from these PRs to the manual dev deploy yaml file:
https://github.com/communitiesuk/funding-service-design-workflows/pull/43
https://github.com/communitiesuk/funding-service-design-workflows/pull/45
N/A
N/A

FS 2385: Copy concurrency keys from Workflow repo Application store

---

db/queries/reporting/queries.py
requirements-dev.txt
requirements.txt
tests/conftest.py
tests/helpers.py
tests/test_reports.py

https://digital.dclg.gov.uk/jira/browse/FS-2464
Include the key application report metrics for welsh applications
usual 'pytest' command will cover these changes as test_reports.py

add welsh support to reporting for COF

---

config/envs/default.py
config/envs/unit_testing.py

- Adds default env variables to config

BAU: Add AWS config as env variables

---

api/routes/application/routes.py
external_services/models/round.py
tests/conftest.py

https://digital.dclg.gov.uk/jira/browse/FS-2871
Links to: https://digital.dclg.gov.uk/jira/browse/FS-2871
Provide contact email information in the notification configuration sent to the notification service.
pytest

add contact email info to round class

---

.github/workflows/deploy.yml
.github/workflows/package.yml
.github/workflows/tag-to-release.yaml
Dockerfile
Procfile
README.md

https://dluhcdigital.atlassian.net/browse/FS-3131
Create image when checking in code
Create image when tagging or pushing code so the images are available for deployment.

FH-3131 Add paketo build into workflow

---

.github/workflows/deploy.yml
.github/workflows/tag-to-release.yaml

* Updating deploy and tag to release to utilise funding-service-design, not funding-design-service
+ref: FS-3222
+semver: minor
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

FS-3222: Updating rearranged fsd

---

.github/workflows/deploy.yml

https://dluhcdigital.atlassian.net/browse/FS-3074
Split out the pre-deploy unit tests when deploying AWS

FS-3074 split aws pre deploy

---

requirements-dev.in
requirements-dev.txt
requirements.in
requirements.txt

Bumped utils version to pickup fixed list of dependencies

Bau fix bs4 dependencies

---

api/routes/application/routes.py
db/queries/feedback/queries.py
db/queries/statuses/queries.py
external_services/models/round.py
tests/conftest.py
tests/test_reports.py
tests/test_routes.py

- When updating status of applications, we need to consider feedback now (if it's enabled)
- Also when we submit feedback we can update the application status too to check if complete

FS-3324: Update application status when post feedback

---

config/envs/default.py
copilot/environments/addons/assessment-import-queue.yml
copilot/environments/addons/form-uploads.yml
copilot/environments/addons/funding-service-magic-links.yml
copilot/fsd-application-store/manifest.yml
external_services/aws.py

Updating the code to include S3 and SQS credentials when building using copilot
- [ N/A ] Unit tests and other appropriate tests added or updated
- [ N/A ] README and other documentation has been updated / added (if needed)
- [ X ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

FS-3089 - SQS and S3 additions for copilot deploy

---

api/routes/application/routes.py
db/queries/form/queries.py
db/queries/statuses/queries.py
pytest.ini
requirements-dev.txt
requirements.txt
tests/test_application_status.py
tests/test_reports.py
tests/test_routes.py

Refactoring the application/form/question status code for easier testing, before adding new logic to this as part of the ticket

fs-3356 prep work - refactoring statuses for easier testing

---

README.md
scripts/README.md
scripts/send_application_on_closure.py
tests/conftest.py
tests/test_send_app_on_closure.py

https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?quickFilter=343&selectedIssue=FS-3277
This PR introduces refactoring and testing for the existing "send_application_on_closure" script, ensuring its compatibility with COFR3W2. Furthermore, it incorporates the logic to send contents of the individual application contents as required.
unit tests

FS-3277-update-send-application-on-closure-script-for-COFR3W2

---

.github/workflows/copilot_deploy.yml
.github/workflows/deploy.yml
.github/workflows/environment.yml
copilot/fsd-application-store/addons/fsd-application-store-cluster.yml

https://dluhcdigital.atlassian.net/browse/FS-3718
Amend the workflows so deployment to AWS dev happens on every commit, and deployment to AWS test happens on merge to master.  Also split out so all environments go via a common module.

FS-3718 - Amend workflow to deploy automatically

---

db/queries/application/queries.py
db/queries/reporting/queries.py

Patch on type checking best practice

pre-commit-fix

---

copilot/fsd-application-store/manifest.yml

* Adding uat and production values to copilot config
+ref: FS-3780
+semver: minor
- [N/A] Unit tests and other appropriate tests added or updated
- [N/A] README and other documentation has been updated / added (if needed)
- [*] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

FS-3780 Updating manifest

---

.github/workflows/copilot_deploy.yml
copilot/fsd-application-store/manifest.yml

Add database migration scripts to the workflow
Double task count
+ref: FS-3799
+semver: minor

Increase task count and add in migration scripts

---

.github/workflows/deploy.yml
.github/workflows/manual-dev-deploy.yaml

Updated expired e2e test token
Run e2e tests

Updated expired tokens

---

.github/workflows/copilot_deploy.yml
copilot/fsd-application-store/manifest.yml

- Change `production` to `prod` on copilot configuration

BAU: Change production to prod on copilot_deploy.yml

---

copilot/fsd-application-store/addons/fsd-application-store-cluster.yml

Add bastion sg to the bastion map in copilot

BAU - Add bastion sg to copilot for prod

---

requirements-dev.txt
requirements.txt

Reverts communitiesuk/funding-service-design-application-store#266

Revert "Bump werkzeug from 2.2.3 to 2.3.8"

---

copilot/fsd-application-store/addons/fsd-application-store-cluster.yml

FS-3880 - Change DB storage-at-rest to be encrypted as a result of PEN testing
NOTE: Deletes the database so data re-migration is required.

FS-3880 - Encrypt DBs

---

copilot/fsd-application-store/addons/fsd-application-store-cluster.yml

Add s3 form-upload bucket permissions

BAU - extend s3 permissions

---

scripts/send_application_reminder.py

- dynamically pass the fund name, deadline date, contact help email to the Notification service
https://dluhcdigital.atlassian.net/jira/software/c/projects/FS/boards/50?selectedIssue=FS-384

template-contents-fix/FS-3845-send-application-reminder-script-automation

---

.env.development
api/routes/application/routes.py
api/routes/queues/routes.py
requirements-dev.txt
requirements.in
requirements.txt

https://dluhcdigital.atlassian.net/browse/FS-3703
Synchronize queue attributes settings in localstack similar to the AWS import queue attributes
- bumped utils & remove TODO comments
1. Rebuild the localstack container
`docker compose down localstack`
`docker compose up localstack`
2. Rebuild assessment-store & application-store
`docker compose up application-store --build`
`docker compose up assessment-store --build`
3. Submit an application & observe the automatic import works as expected

FS-3703-workout-msg-duplication-settings

---

app.py
scripts/send_application_reminder.py

- There was a bug where users were receiving duplicate email from the reminder script. The bug has now been fixed. The user should now only receive one email per account for each round
- Improved the log message that counts the unique account emails instead of applications

bug-fix/FS-3845-send-application-reminder-script-automation

---

app.py
scripts/send_application_reminder.py

aws built-in method to be used to be implemented to scheduler the task instead of flask scheduler

remove-scheduler/FS-3845-send-application-reminder-script-automation

---

config/key_report_mappings/cof_key_report_mapping.py
config/key_report_mappings/mappings.py

https://dluhcdigital.atlassian.net/browse/FS-3990
COF key report mapping was missing, have made a generic one for future use on cof rounds
Click the Export applicants feedback information button

FS-3990 Adding generic cof round mapping

---

copilot/fsd-application-store/addons/fsd-application-store-cluster.yml

https://dluhcdigital.atlassian.net/browse/FS-3945
Increase retention from 1 day to 8
Applied to dev and checked retention period has been amended.

FS-3945 Increase retention period to 8 days

---

api/routes/application/routes.py
config/envs/default.py
external_services/__init__.py
external_services/data.py
external_services/models/account.py
external_services/models/notification.py
requirements-dev.txt
requirements.in
requirements.txt
tests/conftest.py
tests/test_routes.py

https://dluhcdigital.atlassian.net/browse/FS-4036
- Added logic for EOI submit application
- Added Notify templates for EOI

FS-4036 Added logic for EOI submit application

---

api/routes/application/routes.py
config/key_report_mappings/cof_eoi_key_report_mapping.py
config/key_report_mappings/mappings.py
db/queries/feedback/queries.py
tests/test_all_feedbacks.py

FS-4036
- Added mapping report for EOI
- Extract `lead_contact name` from the form (required for the notify emails)
- Some code improvements

FS-4036 added mapping report for EOI

---

config/key_report_mappings/cof_eoi_key_report_mapping.py

Updating form names in config to match new EOI names

fs-4143 updating report mappings iwth new form names

---

config/key_report_mappings/cof_eoi_key_report_mapping.py

https://dluhcdigital.atlassian.net/browse/FS-4211
Added mapping report fields for COF-EOI

FS-4211 added mapping report field for COF-EOI

---

config/key_report_mappings/cof_eoi_key_report_mapping.py

Added welsh form names to EOI report mapping

fs-4243 added welsh form names

---

api/routes/application/routes.py

- Pass language so EOI we can pull back the correct EOI schema (welsh or english)
- https://github.com/communitiesuk/funding-service-design-fund-store/pull/263
---

FS-4192: Add Welsh compatibility for EOI

---

.github/workflows/copilot_deploy.yml

Correcting trigger paths for deployments to prevent need for manual deploys

Bau fix trigger paths

---

config/key_report_mappings/cof_key_report_mapping.py
config/key_report_mappings/mappings.py
tests/test_queries.py

Updating column mappings to include missing IDs 
Launch the assessment tool
Click 'Export feedback survey responses' for the following funds and check they all include data in the `applicant_email` column
- COF R4W1
- COF EOI
- COF R3W3

Fs 4308 feedback export

---

api/routes/application/routes.py
external_services/models/fund.py
external_services/models/round.py
requirements-dev.txt
requirements.txt
tests/api_data/get_endpoint_data.json
tests/conftest.py
tests/test_queries.py
tests/test_routes.py

https://dluhcdigital.atlassian.net/browse/FS-2940
Adding language and fund info for application submit txt export

FS-2940 - Adding fund info for export txt file

---

api/routes/application/routes.py
external_services/models/round.py

- Start consuming new `is_expression_of_interest` property instead of checking the short name
---

FS-4232: Add "is_expression_of_interest" as a proper round property

---

tests/seed_data/HSRA_R1_all_forms.json

https://dluhcdigital.atlassian.net/browse/FFE-266
- seed data updated as per requirements change

FS:4413 HSRA application text change

---

config/envs/default.py

remove VCAP specific config
VCAP services is specific to PaaS, so can be safely removed post-PaaS migration.
Deployment should still be successful

BAU: remove VCAP specific config

---

scripts/send_application_on_closure.py

Quick fix to add missing parameter `full_name` in call to Notification.send()

Fix to include full_name in Notification.send()

---

scripts/send_application_on_closure.py

Fix for send_application_on_closure script (missing index on application)

Fix for send_application_on_closure script

---

scripts/send_application_on_closure.py

fix application deadline reminder manual trigger

fix application deadline reminder manual trigger

---

config/envs/default.py
pytest.ini
requirements-dev.txt
requirements.in
requirements.txt

fs-4647 bump utils

---

api/routes/application/routes.py
db/queries/statuses/queries.py
db/queries/updating/queries.py
tests/conftest.py
tests/test_routes.py

While user updating the application and round closed user responses will be saved & redirect them to the fund close page, but there will be trigger to that behaviour.
https://dluhcdigital.atlassian.net/browse/FS-4666

FS-4666 : while application update check is round is closed or not 

---

pyproject.toml
uv.lock

Forgot to add ruff to the dependency list in previous PR

adding ruff dependency
